### ISSUE TITLE
discussion: computing influence scores 2017-12-15

### ISSUE THREAD

**Issue by lexingxie** [csmetrics/influencemap#12]
TODO 
* option to separate co-authors flower vs everyone else flower ✓
* option to exclude self-citations ✓

REVISIT LATER

* normalize citation credit made by one paper?  1/(# of references) 

* weight citation edge by the number of citations that the citing paper has? 
  (this has a downside of discounting more recent papers) 
  - is there any ideas for weighting papers by age?

**Comment by alexandersoen** [comment]
* Excluding self-citations requires input from the user to return a list of author ids and paper ids associated to those authors
* Separate co-authors flower vs everyone else flower can be fixed in the "front-end" part of producing the flower

**Comment by lexingxie** [comment]
> co-authors flower vs everyone else flower can be fixed 
> in the "front-end" part of producing the flower

agreed! 

> Excluding self-citations requires input from the user to 
> return a list of author ids and paper ids associated to those authors

i agree.  
there're two separable concerns here: 
(a) "coming up with the list of paperIDs associated with author/conf/journal" (from the webapp, or assume a list as is done currently)
(b) "plotting in/out flowers and excluding paperIDs in (a)"  

are we on the same page?

**Comment by alexandersoen** [comment]
* Include coauthors as a self-cited paper ✓
