### ISSUE TITLE
Enhance search bar auto complete

### ISSUE THREAD

**Issue by BennoXxx** [csmetrics/influencemap#16]
-Allow the search bar to search for and display non authors as acronyms
-Increase the size of the option display box
-See if there are any possible efficiency improvements

**Comment by lexingxie** [comment]
> -Allow the search bar to search for and display non authors as acronyms

if this is done, e.g. showing "ICML - International Conf ..." 

> -Increase the size of the option display box

then this is not needed. 

i.e. acronym is hopefully enough to disambiguate the last two options?
![image](https://user-images.githubusercontent.com/2434228/35494438-aaf1465c-050e-11e8-9722-475f1badac02.png)

**Comment by BennoXxx** [comment]
User can now search using acronyms and results with long names will show acronyms at the left (at the moment the acronyms are created trivially by removing the words of, the, and, on, for. This does not apply for authors.

The search also checks whether each word in a search is in the suggestion, i.e. typing 'eliot moss' will now match the suggestion 'j eliot b moss'.
