### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by hhung** [csmetrics/influencemap#61]
Hello, I can no longer search or create new flowers. I think there's a problem with the server as I also get an internal server error whenever I click on a profile.

**Comment by shinminjeong** [comment]
Hi @hhung 
We shut down the database server for server relocation. It will be back soon.
Thank you for reporting this!

**Comment by matteo-ds** [comment]
I'm having the same problems right now, when will the servers be back up again please? It's been this way for a couple of weeks already.

For instance, I'm unable to access Perlis's flower: http://115.146.86.238/submit/?id=Ceilrk~QWxhbiBKIFBlcmxpcw

**Comment by shinminjeong** [comment]
Hi @matteo-ds 
The server is now up! Thank you for reporting 👍
