### ISSUE TITLE
check how citation/reference weights are computed

### ISSUE THREAD

**Issue by lexingxie** [csmetrics/influencemap#9]
and write down in an markdown file the formula for computing weights.

**Comment by lexingxie** [comment]
figure out how the mysterious 17.xx came about

**Comment by BennoXxx** [comment]
The original formula for computing weights has been documented in the primary  [README.md](https://github.com/csmetrics/influencemap/blob/master/README.md) file. The method for calculating these values changed so the mysterious 17.xx was no longer relevant.
